name: timeago_flutter_tec
description: Timeago Widget for Flutter to create fuzzy timestamps. (e.g. "15 minutes ago").
version: 4.0.0
homepage: https://github.com/zektec/timeago_tec
issue_tracker: https://github.com/zektec/timeago_tec/issues

topics:
  - date
  - time
  - timestamp
  - localization
  - internationalization

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  timeago_tec: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
