name: timeago_flutter_example_tec
description: A Flutter example for timeago_flutter_tec package on the top of timeago_tec.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  timeago_flutter_tec: 
    path: ../timeago_flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

publish_to: none
