name: timeago_tec
description: >
  A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
version: 4.0.0
homepage: https://github.com/zektec/timeago_tec
issue_tracker: https://github.com/zektec/timeago_tec/issues

topics:
  - date
  - time
  - timestamp
  - localization
  - internationalization

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  intl: ">=0.18.0 <0.21.0"

dev_dependencies:
  test: ^1.21.4
  build_runner: ^2.2.0
  build_web_compilers: ^4.0.6
